### PR TITLE
RFCT: Start breaking up the UI into components

### PR DESCRIPTION
**Pull request by max-ishere**
This PR is part of my implementation of #85. I've noticed that it is not easy to "just do X", pretty much everything is tangled up into about 3 functions (a single `fn update` that does everything in the app, the clock, the power buttons, the login, everything; a view generated by Relm; and the init function that sets absolutely every component up) that are "broken up" into separate steps (functions), but when you try to pull out one step into a separate component something else needs to be pulled out as well.

So I decided it would be easiest to move as much of the UI components out of the `Greeter` component before tackling the mess of a grid in the login ui.

Anyways, here are the changes:

- Separate the clock from the Greeter component
- Replace chrono with jiff
- Add TOML config options for the clock widget
- Minor misc. improvements

The key benefit is the customizability of the clock and use of `jiff` crate, which, unlike `chrono`, doesn't require timezones to be initialized before threading.

### CODE REVIEW

**Comment by rharish101** [comment]
Rebased it on the latest main. Do you plan on adding more to this PR, or should I merge it? IMO it seems complete as a PR for the clock widget.

**Comment by max-ishere** [comment]
It is complete, but I haven't tested the rebased version.

**Comment by max-ishere** [comment]
Sorry for the delay, life happened and I forgot to come back to this.

So, looking at the diff before and after, it seems that the only change is the #54 merging. I will try out this rebased version, but I doubt it will be broken.

**Comment by max-ishere** [comment]
LGTM for the rebase.

As for the CI failure, well, this seems to be a Rust version specific issue? The suggestion from clippy not only doesnt exist on my machine, it fails to complile if applied.

**Comment by max-ishere** [comment]
I also rebased this onto master so this should be ready to merge now... The CI is bugging me though, because it will probably keep failing all the later checks.

**Comment by rharish101** [comment]
I got it to compile with the CI-suggested fix with Rust 1.75. Could you try it out and see if it compiles for you now?

**Comment by max-ishere** [comment]
I forgot to do a `<'_>` :facepalm:

**Comment by max-ishere** [comment]
Yup, it compiles

**Pull request merged**
